[custom]
# Ao abrir o jogo: desativa animações e blur do Hyprland
start=hyprctl keyword animations:enabled 0; hyprctl keyword decoration:blur:enabled 0

# Ao fechar o jogo: devolve as animações e blur do End4
end=hyprctl keyword animations:enabled 1; hyprctl keyword decoration:blur:enabled 1
